#!/bin/bash

case $1 in
collect)
  cp ~/.vimrc vimrc
  cp ~/.screenrc screenrc
  cp ~/.xmonad/xmonad.hs xmonad/xmonad.hs
  cp ~/.config/dunstrc config/dunstrc
  cp ~/.xinitrc xinitrc
  cp ~/.xprofile xprofile
  cp ~/.zshenv zshenv
  cp ~/.zshrc  zshrc
  cp -R ~/.vim/*  vim
  if [ -e vim/colors ]; then
    echo -n "Entferne molokai color scheme..."
    rm -R vim/colors
    rm vim/README.md
    echo " Done"
  fi
  cp -R ~/.zsh/* zsh
  if [ -e zsh/git-prompt ]; then
    echo -n "Entferne zsh-git-prompt..."
    rm -R zsh/git-prompt
    rm zsh/zshrc.sh
    echo " Done"
  fi
  cp ~/.xmobarrc xmobarrc
  ;;
deploy)
  git submodules update
  cp vimrc ~/.vimrc
  cp screenrc ~/.screenrc
  cp xmonad/xmonad.hs ~/.xmonad/xmonad.hs
  cp config/dunstrc ~/.config/dunstrc
  cp xinitrc ~/.xinitrc
  cp xprofile ~/.xprofile
  cp zshenv ~/.zshenv
  cp zshrc ~/.zshrc
  cp -r external/zsh-git-prompt/ ~/.zsh/
  cp -r external/molokai/* ~/.vim/
  cp xmobarrc ~/.xmobarrc
  ;;
*)
  echo "No Argument specified, usage:"
  echo "./confs [deploy|collect]"
esac
