#!/bin/bash

case $1 in
collect)
  cp ~/.vimrc vimrc
  cp ~/.Xdefaults Xdefaults
  cp ~/.screenrc screenrc
  cp ~/.xmonad/xmonad.hs xmonad/xmonad.hs
  cp ~/.config/dunstrc config/dunstrc
  cp ~/.xinitrc xinitrc
  cp ~/.xprofile xprofile
  cp ~/.zshenv zshenv
  cp ~/.zshrc  zshrc
  cp -R ~/.vim/*  vim
  if [ -e vim/colors ]; then
    echo -n "Entferne molokai color scheme..."
    rm -R vim/colors
    rm vim/README.md
    echo " Done"
  fi
  cp -R ~/.zsh/* zsh/
  if [ -e zsh/external/LS_COLORS ]; then
    echo -n "Entferne LS_COLORS aus zsh/external..."
    rm -R zsh/external/LS_COLORS
    echo " Done"
  fi
  cp ~/.xmobarrc xmobarrc
  ;;
deploy)
  git submodule update
  cp vimrc ~/.vimrc
  cp Xdefaults ~/.Xdefaults
  cp screenrc ~/.screenrc
  cp xmonad/xmonad.hs ~/.xmonad/xmonad.hs
  cp config/dunstrc ~/.config/dunstrc
  cp xinitrc ~/.xinitrc
  cp xprofile ~/.xprofile
  cp zshenv ~/.zshenv
  cp zshrc ~/.zshrc
  cp -r -T zsh ~/.zsh
  cp -r external/molokai/* ~/.vim/
  cp -r external/LS_COLORS ~/.zsh/
  cp xmobarrc ~/.xmobarrc
  ;;
*)
  echo "No Argument specified, usage:"
  echo "./confs [deploy|collect]"
esac
