#!/bin/bash

case $1 in
collect)
  cp ~/.vimrc vimrc
  cp ~/.Xdefaults Xdefaults
  cp ~/.screenrc screenrc
  cp ~/.xmonad/xmonad.hs xmonad/xmonad.hs
  cp ~/.config/dunstrc config/dunstrc
  cp ~/.xinitrc xinitrc
  cp ~/.xprofile xprofile
  cp ~/.zshenv zshenv
  cp ~/.zshrc  zshrc
  cp -R ~/.vim/*  vim
  if [ -e vim/colors ]; then
    echo -n "Entferne molokai color scheme und vim-addons..."
    rm -R vim/colors
    rm vim/README.md
    rm -fR vim/vim-addons
    echo " Done"
  fi
  cp -R ~/.zsh/* zsh/
  if [ -e zsh/external/LS_COLORS ]; then
    echo -n "Entferne LS_COLORS aus zsh/external..."
    rm -R zsh/external/LS_COLORS
    echo " Done"
  fi
  cp ~/.xmobarrc xmobarrc
  cp ~/.gitconfig gitconfig
  ;;
deploy)
  git submodule init
  git submodule update
  cp vimrc ~/.vimrc
  cp Xdefaults ~/.Xdefaults
  cp screenrc ~/.screenrc
  cp xmonad/xmonad.hs ~/.xmonad/xmonad.hs
  cp config/dunstrc ~/.config/dunstrc
  cp xinitrc ~/.xinitrc
  cp xprofile ~/.xprofile
  cp zshenv ~/.zshenv
  cp zshrc ~/.zshrc
  cp -r -T zsh ~/.zsh
  cp -r external/molokai/* ~/.vim/
  if [ ! -e ~/.zsh/external ]; then
    echo -n "Erstelle ~/.zsh/external/..."
    mkdir ~/.zsh/external
    echo " Done"
  fi
  cp -r external/LS_COLORS ~/.zsh/external/
  if [[ $(grep NORMAL ~/.zsh/external/LS_COLORS/LS_COLORS) ]]; then
    echo "Unpatched Version of LS_COLORS detected, patching..."
    patch ~/.zsh/external/LS_COLORS/LS_COLORS patches/LS_COLORS.patch
    echo "Done"
  fi
  cp xmobarrc ~/.xmobarrc
  cp gitconfig ~/.gitconfig
  ;;
*)
  echo "No Argument specified, usage:"
  echo "./confs [deploy|collect]"
esac
